"""Add date of birth to people

Revision ID: 7bbce0974d28
Revises: 1bb268370800
Create Date: 2020-06-27 01:00:38.811687

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = '7bbce0974d28'
down_revision = '1bb268370800'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('date_of_birth', sa.Date(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'date_of_birth')
    # ### end Alembic commands ###
